In [17]:
import geopandas as gpd
import glob
from pathlib import Path
import netCDF4 as ncd
import numpy as np

In [18]:
hru_shp = Path('../sagehen_maps/HRUs.shp')
hru_data = gpd.read_file(hru_shp)

In [19]:
hru_data


AREA  PERIMETER  TP_JAG_MF_  TP_JAG_MF1  GRID_CODE  \
0    304200.0     4140.0           2           1          1   
1    156600.0     2880.0           3           2          2   
2     53100.0     1440.0           4           3          3   
3    441000.0     5040.0           5           4          4   
4    106200.0     2460.0           6           5          5   
..        ...        ...         ...         ...        ...   
123  372600.0     4260.0         125         124        124   
124  197100.0     2940.0         126         125        125   
125  219600.0     2400.0         127         126        126   
126  171900.0     2100.0         128         127        127   
127   55800.0     1500.0         129         128        128   

                                              geometry  
0    POLYGON ((-2046220 2089229.875, -2046250 20892...  
1    POLYGON ((-2046220 2089229.875, -2046220 20891...  
2    POLYGON ((-2046040 2088869.875, -2046040 20888...  
3    POLYGON ((-2045890 2088749.875, -2045860 20887...  
4    POLYGON ((-2046130 2088689.875, -2046130 20886...  
..                                                 ...  
123  POLYGON ((-2046040 2083829.875, -2046010 20838...  
124  POLYGON ((-2045920 2083769.875, -2045890 20837...  
125  POLYGON ((-2045800 2083709.875, -2045800 20836...  
126  POLYGON ((-2045230 2083649.875, -2045230 20836...  
127  POLYGON ((-2045650 2083349.875, -2045620 20833...  

[128 rows x 6 columns]

In [20]:
hru_data.GRID_CODE.values


array([  1,   2,   3,   4,   5,  15,   6,   7,   9,   8,  10,  11,  12,
        13,  17,  14,  16,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  35,  33,  32,  34,  36,  37,  38,  49,
        39,  40,  41,  57,  42,  43,  44,  47,  45,  46,  48,  50,  51,
        52,  53,  54,  55,  56,  58,  59,  60,  76,  61,  62,  63,  65,
        66,  64,  67,  68,  69,  70,  71,  72,  73,  74,  75,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  91,  90,  89,
        92,  93,  94,  95,  96,  97,  98, 104,  99, 100, 101, 102, 103,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 123, 120, 121, 122, 124, 125, 126, 127, 128], dtype=int64)

In [21]:
hru_data.index.values


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127], dtype=int64)

In [22]:
hru_dsort = hru_data.iloc[hru_data['GRID_CODE'].sort_values().index.values]

In [23]:
sqm2acres = 0.000247105
hru_dsort.AREA.values*sqm2acres

array([ 75.169341 ,  38.696643 ,  13.1212755, 108.973305 ,  26.242551 ,
        66.9407445,  96.7416075, 182.5858845,  61.6032765,  46.0356615,
        87.4010385,  14.0108535,  19.570716 , 153.007416 , 136.995012 ,
        91.181745 ,  49.5939735,  35.138331 ,  78.5052585,  67.8303225,
        42.0325605,  40.6981935,  39.8086155,  33.803964 ,  72.7230015,
        18.9035325,  48.7043955, 160.3464345,  47.8148175, 102.0790755,
        80.506809 ,  21.1274775,  59.156937 ,  20.015505 ,  36.2503035,
        35.3607255,  35.8055145,  27.576918 ,  27.3545235,  64.7167995,
        23.3514225,  76.948497 ,  21.349872 ,  24.463395 ,  29.5784685,
        22.0170555,  94.0728735,  13.788459 ,  25.1305785,  21.349872 ,
        29.5784685,  56.043414 ,  84.2875155,  47.147634 ,  26.9097345,
        36.2503035,  26.242551 ,  16.901982 ,  30.0232575,  81.396387 ,
        20.905083 ,  28.021707 , 278.6603085,  23.3514225,  26.0201565,
        60.046515 ,  14.9004315,  42.699744 ,  15.567615 ,  28.4

In [24]:
hru_data.crs

{'init': 'epsg:5069'}

In [25]:
hru_dsort.to_crs(epsg=4326).geometry.centroid.x

0     -120.264641
1     -120.262843
2     -120.259378
3     -120.251370
4     -120.260035
          ...    
123   -120.250096
124   -120.246071
125   -120.242391
126   -120.237160
127   -120.238025
Length: 128, dtype: float64

In [26]:
import netCDF4 as ncd
import numpy as np
filencf = ncd.Dataset('../sagehen_prms6/prms6/prms_grid_v3-Copy1.nc','a')

In [27]:
print(filencf)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    dimensions(sizes): nsegment(15), nobs(1), nhru(128), nssr(128), ngw(128), ndepl(1), ndeplval(1408), nmonths(12), ndays(366), ntemp(2), nrain(2)
    variables(dimensions): float32 albset_snm(), float32 ssr2gw_rate(nssr), float32 tmax_allrain_offset(nmonths,nhr), int32 runoff_units(), float32 fastcoef_lin(nhr), float32 soil_rechr_max_frac(nhr), float32 soil_rechr_init_frac(nhr), float32 smidx_coef(nhr), float32 transp_tmax(nhr), float32 slowcoef_lin(nhr), float32 radadj_slope(nmonths,nhr), float32 snarea_thresh(nhr), float32 radmax(nmonths,nhr), float32 den_init(), float32 fastcoef_sq(nhr), float32 albset_sna(), float32 ssr2gw_exp(nhr), float32 freeh2o_cap(nhr), float32 tmax_allsnow(nmonths,nhr), float32 soil_moist_max(nhr), float32 dday_slope(nmonths,nhr), float32 smidx_exp(nhr), float32 dday_intcp(nmonths,nhr), float32 snarea_curve(ndeplval), int32 transp_end(nhr), float32 carea_max(nhr), float32 

In [28]:
filencf.dimensions.keys()

odict_keys(['nsegment', 'nobs', 'nhru', 'nssr', 'ngw', 'ndepl', 'ndeplval', 'nmonths', 'ndays', 'ntemp', 'nrain'])

In [29]:
hru_lon = filencf.createVariable('hru_lon', np.dtype(np.float32).char, ('nhru'))
hru_x = filencf.createVariable('hru_x', np.dtype(np.float32).char, ('nhru'))
hru_y = filencf.createVariable('hru_y', np.dtype(np.float32).char, ('nhru'))

In [30]:
hru_lon[:] = hru_dsort.to_crs(epsg=4326).geometry.centroid.x.values
hru_x[:] = hru_dsort.to_crs(epsg=4326).geometry.centroid.x.values
hru_y[:] = hru_dsort.to_crs(epsg=4326).geometry.centroid.y.values

In [31]:
filencf.close()